CREATE TABLE IF NOT EXISTS solutions(
    id INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    problem_id INT(11) NOT NULL,
    problem_type VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    solver VARCHAR(255) NOT NULL,
    score INT NULL,
    content TEXT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);