name: Rust Build and Test

on:
  push:
    branches: [ "main", "add-rust-cli-sum" ]
  pull_request:
    branches: [ "main", "add-rust-cli-sum" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build
      run: cargo build --verbose
      working-directory: ./sum-cli

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./sum-cli
